= Actions types for anonymization
:description: Description of all the possible actions type for anonymization

== Overview
Action types are mechanisms used to anonymize specific values in the exported data. A value can have one or multiple actions associated with it. If no actions are explicitly specified in the configuration for a particular value, it will default to a predefined action as described in the page xref:configuration-for-anonymization.adoc[Configure the anonymization].

Additionally, you can define a fallback mechanism in case the primary action does not work or does not find a match (for example, using the `regex_replace` action).

== Hash - Hash a value

Replace the values by a Hash, this allows to remove readable values but keeps the cardinality. Safe hash function should be used ( SHA-256 for instance )

*Usage* : Value containing sensitive information but on which you want to have accurate statistic and the ability to see the impact on the process execution. 

*Parameters* : 

*value* : the algorithm to use for hashing. Optional, default to SHA-512 

Sample configuration : 
[source,yaml]
----
    arch_process_instance:
      stringindex1:
        actions:
          - action: hash
            value: SHA-256 
----

== Replace - Replace a value

Replace the value with a specified value ( which can be empty ) 

*Usage* : Value containing sensitive information you want to hide.

*Parameters* :

*value* : The value used to replace the current field. Default value empty

Sample configuration :
[source,yaml]
----
    arch_flownode_instance:
      displayname:
        actions:
          - action: REPLACE
            value: 'hidden'
----

== Replace_with_other - Replace a value by another column value of the same table

Replace a value by another value of the same table and line.

*Usage* : Value containing sensitive information you want to replace with another non sensitive meaningful value in the same table.

*Parameters* :

*value* : column name of the column to be use to replace the value.  No Default , mandatory

Sample configuration :
[source,yaml]
----
    arch_flownode_instance:
      displayname:
        actions:
          - action: REPLACE_WITH_OTHER
            value: name
----
== Regex_replace - Replace a value matching a regex expression

Replace the value if the regexp match and use the matching group to create the new value.

if multiple part of the value match , they are all replace. ( Behavior similar to  Matcher.replaceAll ) 

If none of the regexp match , allow to configure a fallback which can be any of the other action. 

*Usage* : Value containing some sensitive information with other non sensitive one and you want to keep the non sensitive information. 

*Parameters* : 

*pattern* : The regular expression to match  Default , mandatory

*value* : The replacement pattern ( including captured group ) to used to change the value. No Default , mandatory

*fallback* : action to apply if no regexp match.

Sample configuration : 
[source,yaml]
----
    arch_process_comment:
      content:
        actions:
          - action: regex_replace
            pattern: contract (\d+) is ready for user (\S+)\.(\S+)
            value: contract XXXX is ready for $2
          - action: regex_replace
            pattern: The task Allocate repair agent on car (\S+) (is now assigned to .*)
            value: The task Allocate repair agent on car *** $2
        fallback:
          - action: replace
            value: hidden comment
----

== Keep - Keep a value

Keep the value, no anonymization done. 

*Parameters*: none

Sample configuration :
[source,yaml]
----
    arch_flownode_instance:
      displayname:
        actions:
          - action: KEEP
----

== Remove_line - Remove a full line

Remove the whole data line ( only possible on data contract and comment ) 

*Parameters* : 
optional where clause expressed as a regex to match with the value for the configured column. 

Sample configuration :
[source,yaml]
----
arch_contract_data:
  val:
    actions:
    - action: remove_line
      where:
        name: "input\.list\.*"
----