= How-to configure the anonymization in the CLI
:description: Learn how-to fine-tune the anonymization in the CLI

== Default anonymization
Using the command `export` of the export tool will activate automatically the anonymization.

[NOTE]
====
In case you don't want to activate the anonymization during your export, you can add the argument `-a=false` at the end of the `export` command.
====

Exported data will be anonymized by default to avoid sensitive data leak or with a specified configuration of your own. 

=== List of tables anonymized by default

This section lists the tables being exported and identified fields that may contain sensitive information. These fields are handled with specific rules to ensure data security.

==== arch_process_instance

The `arch_process_instance` table contains information related to process instances. While it primarily includes technical data necessary for BPI, certain fields within this table may contain sensitive information and require special handling:

* **description**: 
** **Default Handling**: KEEP
** **Details**: This field contains the description of the process instance itself. Although it might contain sensitive data (e.g., company names, departments, addresses), this is usually not the case.

* **stringindex1, stringindex2, stringindex3, stringindex4, stringindex5**: 
** **Default Handling**: HASH
** **Details**: These fields can include specific Groovy code, which may expose sensitive data. Therefore, they are hashed by default to maintain data security.

IMPORTANT: this is a work in progress!!

== Advanced anonymization

=== Generate a sample configuration for data anonymization